### ISSUE TITLE
安装时遇到了一点问题……

### ISSUE THREAD

**Issue by CZnemo12138** [liuxinwang/horizon#1]
大佬，我按照操作步骤，到“初始化admin用户”这一步的时候出现了一些问题，init脚本和数据库结构有些出入，导致数据不能正确插入到表中。我尝试这手动修改了一些数据，然后登陆的时候，首页提示
![95fe047068328dc784c3cd63b3999d8](https://github.com/liuxinwang/horizon/assets/83337369/56ce784b-de5d-4f5a-a77a-df08d4a0244b)

后台提示
![c218518e78881dec68cd5e81544bace](https://github.com/liuxinwang/horizon/assets/83337369/2a69656c-8706-4134-9421-c72c213c5721)
麻烦帮忙看一下……

**Comment by liuxinwang** [comment]
我看一下

**Comment by liuxinwang** [comment]
-- insert admin user role
INSERT INTO `user_roles`(`user_id`, `role_id`)VALUES('1', 'admin');

初始化admin 用户的role

**Comment by CZnemo12138** [comment]
![image](https://github.com/liuxinwang/horizon/assets/83337369/f2fd20c0-8381-4400-91e9-ccf86a549b0f)

**Comment by liuxinwang** [comment]
-- insert role
INSERT INTO `roles`(`id`, `name`, `describe`)VALUES('admin', '系统管理员', '');
admin 角色先初始化

**Comment by CZnemo12138** [comment]
麻烦给个完整的脚本吧

**Comment by liuxinwang** [comment]
参考下最新的 [https://github.com/liuxinwang/horizon/blob/master/scripts/init.sql](url)

**Comment by CZnemo12138** [comment]
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('DISK_UTILIZATION','磁盘使用率',now(),now());这一条还是有点问题，麻烦核实下

**Comment by liuxinwang** [comment]
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('DISK_UTILIZATION','磁盘使用率','%',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('HIGH_RISK_ACCOUNT','高危账号', '个', now(),now());

**Comment by CZnemo12138** [comment]
使用最新的脚本，可以了！
